from PyQt5 import QtCore, QtGui, QtWidgets
from Main import Interface


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 402)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.costPerKgLineEdit = QtWidgets.QLineEdit(self.frame)
        self.costPerKgLineEdit.setObjectName("costPerKgLineEdit")
        self.costPerKgLineEdit.setReadOnly(True)
        self.gridLayout.addWidget(self.costPerKgLineEdit, 6, 3, 1, 1)
        self.nWeeekEstWeightLabel = QtWidgets.QLabel(self.frame)
        self.nWeeekEstWeightLabel.setObjectName("nWeeekEstWeightLabel")
        self.gridLayout.addWidget(self.nWeeekEstWeightLabel, 8, 1, 1, 2)
        self.nWeekEstWeightLineEdit = QtWidgets.QLineEdit(self.frame)
        self.nWeekEstWeightLineEdit.setObjectName("nWeekEstWeightLineEdit")
        self.nWeekEstWeightLineEdit.setReadOnly(True)
        self.gridLayout.addWidget(self.nWeekEstWeightLineEdit, 8, 3, 1, 1)
        self.nWeeekEstCostLabel = QtWidgets.QLabel(self.frame)
        self.nWeeekEstCostLabel.setObjectName("nWeeekEstCostLabel")
        self.gridLayout.addWidget(self.nWeeekEstCostLabel, 9, 1, 1, 2)
        self.nWeekEstCostLineEdit = QtWidgets.QLineEdit(self.frame)
        self.nWeekEstCostLineEdit.setObjectName("nWeekEstCostLineEdit")
        self.nWeekEstCostLineEdit.setReadOnly(True)
        self.gridLayout.addWidget(self.nWeekEstCostLineEdit, 9, 3, 1, 1)
        self.vegNameLabel = QtWidgets.QLabel(self.frame)
        self.vegNameLabel.setObjectName("vegNameLabel")
        self.gridLayout.addWidget(self.vegNameLabel, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 4, 1, 1)
        self.costPerKgLabel = QtWidgets.QLabel(self.frame)
        self.costPerKgLabel.setObjectName("costPerKgLabel")
        self.gridLayout.addWidget(self.costPerKgLabel, 6, 1, 1, 2)
        self.weightLabel = QtWidgets.QLabel(self.frame)
        self.weightLabel.setObjectName("weightLabel")
        self.gridLayout.addWidget(self.weightLabel, 5, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 3, 1, 1)
        self.vegChooseComboBox = QtWidgets.QComboBox(self.frame)
        self.vegChooseComboBox.setObjectName("vegChooseComboBox")
        self.vegChooseComboBox.addItem("")
        self.vegChooseComboBox.addItem("")
        self.vegChooseComboBox.addItem("")
        self.vegChooseComboBox.addItem("")
        self.vegChooseComboBox.addItem("")
        self.gridLayout.addWidget(self.vegChooseComboBox, 3, 3, 1, 1)
        self.weightLineEdit = QtWidgets.QLineEdit(self.frame)
        self.weightLineEdit.setObjectName("weightLineEdit")
        self.weightLineEdit.setReadOnly(True)
        self.gridLayout.addWidget(self.weightLineEdit, 5, 3, 1, 1)
        self.vegNameLabel_2 = QtWidgets.QLabel(self.frame)
        self.vegNameLabel_2.setObjectName("vegNameLabel_2")
        self.gridLayout.addWidget(self.vegNameLabel_2, 0, 1, 1, 3)
        self.totalCostLabel = QtWidgets.QLabel(self.frame)
        self.totalCostLabel.setObjectName("totalCostLabel")
        self.gridLayout.addWidget(self.totalCostLabel, 7, 1, 1, 2)
        self.totalCostLineEdit = QtWidgets.QLineEdit(self.frame)
        self.totalCostLineEdit.setObjectName("totalCostLineEdit")
        self.totalCostLineEdit.setReadOnly(True)
        self.gridLayout.addWidget(self.totalCostLineEdit, 7, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.totalPBar = QtWidgets.QProgressBar(self.frame_2)
        self.totalPBar.setMinimumSize(QtCore.QSize(76, 0))
        self.totalPBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.totalPBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.totalPBar.setStyleSheet("")
        self.totalPBar.setMinimum(0)
        self.totalPBar.setOrientation(QtCore.Qt.Vertical)
        self.totalPBar.setInvertedAppearance(False)
        self.totalPBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.totalPBar.setObjectName("totalPBar")
        self.gridLayout_2.addWidget(self.totalPBar, 0, 0, 1, 1)
        self.leftoverPBar = QtWidgets.QProgressBar(self.frame_2)
        self.leftoverPBar.setMinimumSize(QtCore.QSize(76, 0))
        self.leftoverPBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftoverPBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leftoverPBar.setStyleSheet("")
        self.leftoverPBar.setMinimum(0)
        self.leftoverPBar.setOrientation(QtCore.Qt.Vertical)
        self.leftoverPBar.setInvertedAppearance(False)
        self.leftoverPBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.leftoverPBar.setObjectName("leftoverPBar")
        self.gridLayout_2.addWidget(self.leftoverPBar, 0, 1, 1, 1)
        self.totalCostLabel_2 = QtWidgets.QLabel(self.frame_2)
        self.totalCostLabel_2.setObjectName("totalCostLabel_2")
        self.gridLayout_2.addWidget(self.totalCostLabel_2, 1, 0, 1, 1)
        self.totalCostLabel_3 = QtWidgets.QLabel(self.frame_2)
        self.totalCostLabel_3.setObjectName("totalCostLabel_3")
        self.gridLayout_2.addWidget(self.totalCostLabel_3, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RefreshButton = QtWidgets.QPushButton(self.tab)
        self.RefreshButton.setObjectName("RefreshButton")
        self.RefreshButton.clicked.connect(self.refresh)    # Added
        self.horizontalLayout.addWidget(self.RefreshButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.quitButton = QtWidgets.QPushButton(self.tab)
        self.quitButton.setObjectName("quitButton")
        self.quitButton.clicked.connect(self.exit_application)  # Added
        self.horizontalLayout.addWidget(self.quitButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(7, 4, item)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.costPerKgLabel_2 = QtWidgets.QLabel(self.frame_4)
        self.costPerKgLabel_2.setObjectName("costPerKgLabel_2")
        self.horizontalLayout_3.addWidget(self.costPerKgLabel_2)
        spacerItem4 = QtWidgets.QSpacerItem(353, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.costPerKgLineEdit_2 = QtWidgets.QLineEdit(self.frame_4)
        self.costPerKgLineEdit_2.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.costPerKgLineEdit_2.setFont(font)
        self.costPerKgLineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.costPerKgLineEdit_2.setObjectName("costPerKgLineEdit_2")
        self.horizontalLayout_3.addWidget(self.costPerKgLineEdit_2)
        self.gridLayout_3.addWidget(self.frame_4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 625, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nWeeekEstWeightLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Next Week Estimate Weight:</span></p></body></html>"))
        self.nWeeekEstCostLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Next Week Estimate Cost:</span></p></body></html>"))
        self.vegNameLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Vegetable: </span></p></body></html>"))
        self.costPerKgLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Cost Per KG:</span></p></body></html>"))
        self.weightLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Weight:</span></p></body></html>"))
        self.vegChooseComboBox.setItemText(0, _translate("MainWindow", "Potato"))
        self.vegChooseComboBox.setItemText(1, _translate("MainWindow", "Tomato"))
        self.vegChooseComboBox.setItemText(2, _translate("MainWindow", "Onion"))
        self.vegChooseComboBox.setItemText(3, _translate("MainWindow", "Carrot"))
        self.vegChooseComboBox.setItemText(4, _translate("MainWindow", "Brinjal"))
        self.vegNameLabel_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">Dashboard</span></p></body></html>"))
        self.totalCostLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Total Cost:</span></p></body></html>"))
        self.totalCostLabel_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Total</span></p></body></html>"))
        self.totalCostLabel_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Leftover</span></p></body></html>"))
        self.RefreshButton.setText(_translate("MainWindow", "Refresh"))
        self.quitButton.setText(_translate("MainWindow", "Quit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Dashboard"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1."))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2."))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3."))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4."))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5."))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6."))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7."))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vegetable"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Standard Requirement"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Leftover"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Requirement"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cost"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Potato"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "40"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "36"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "720"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Tomato"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "35"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "35"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "1365"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "Onion"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "37"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "28"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("MainWindow", "1680"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "Carrot"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("MainWindow", "896"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Brinjal"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "30"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("MainWindow", "23"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("MainWindow", "828"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "Capsicum"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("MainWindow", "792"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "Cucumber"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("MainWindow", "144"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "Cabbage"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("MainWindow", "33"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("MainWindow", "30"))
        item = self.tableWidget.item(7, 4)
        item.setText(_translate("MainWindow", "1080"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.costPerKgLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Total Cost:</span></p></body></html>"))
        self.costPerKgLineEdit_2.setText(_translate("MainWindow", "Rs. 7505"))
        self.costPerKgLineEdit_2.setReadOnly(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Summary"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

    def refresh(self):
        obj = Interface()
        value_list = obj.main()
        value_list = [str(i) for i in value_list]

        height = value_list[0]
        potato_price = value_list[1]
        potato_cost = value_list[2]
        coming_week_weight_req_estimate = value_list[3]
        coming_week_weight_price_estimate = value_list[4]
        prev_day_height = value_list[5]
        max_height = value_list[6]
        weight = value_list[7]

        leftover = float(prev_day_height) / float(max_height) * 100
        total = float(height) / float(max_height) * 100

        self.totalPBar.setProperty("value", total)
        self.leftoverPBar.setProperty("value", leftover)
        self.costPerKgLineEdit.setText(potato_price)
        self.nWeekEstWeightLineEdit.setText(coming_week_weight_req_estimate)
        self.nWeekEstCostLineEdit.setText(coming_week_weight_price_estimate)
        self.weightLineEdit.setText(weight)
        self.totalCostLineEdit.setText(potato_cost)


    def exit_application(self):
        sys.exit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

